<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2024 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/** @var \Tigren\CustomerGroupCatalog\Block\History\Index $block */
$ruleHistory = $block->getRuleHistory();
?>
<style>
    .styled-table {
        width: 100%;
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 1em;
        font-family: 'Arial', sans-serif;
        background-color: #f3f3f3;
        border-radius: 8px 8px 0 0;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }

    .styled-table thead tr {
        background-color: #007bdb;
        color: #ffffff;
        text-align: left;
        font-weight: bold;
    }

    .styled-table th,
    .styled-table td {
        padding: 12px 15px;
        border-right: 1px solid #dddddd;
        text-align: center;
    }

    .styled-table tbody tr {
        border-bottom: 1px solid #dddddd;
    }

    .styled-table tbody tr:nth-of-type(even) {
        background-color: #f3f3f3;
    }

    .no-history {
        text-align: center;
        font-size: 1.2em;
        font-style: italic;
        color: #007bdb;
    }
</style>

<table class="data-table styled-table">
    <thead>
        <tr>
            <th><?php echo __('Order ID') ?></th>
            <th><?php echo __('Customer') ?></th>
            <th><?php echo __('Rule ID') ?></th>
            <th><?php echo __('Created At') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php if (count($ruleHistory) > 0): ?>
            <?php foreach ($ruleHistory as $item): ?>
                <tr>
                    <td>
                        <a href="<?php echo $block->getUrl('sales/order/view', ['order_id' => $item->getOrderId()]); ?>">
                            <?php echo $this->escapeHtml($item->getOrderId()); ?>
                        </a>
                    </td>

                    <td>
                        <a href="<?php echo $block->getUrl('tigrencustomergroupcatalog/history/ruleinfo', ['rule_id' => $item->getRuleId()]); ?>">
                            <?php echo $this->escapeHtml($item->getRuleId());
                            ?>
                        </a>
                    </td>
                    <td><?php echo $this->escapeHtml($item->getCreatedAt()) ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="3" class="no-history"><?php echo __('No rule history found.') ?></td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>