<div id="example">
    <p><?= __('Click the button Tigren_MagentoJS.') ?></p>
    <button id="click-button" data-role="button-click"><?= __('Click Me') ?></button>
</div>

<!-- Sử dụng x-magento-init để truyền dữ liệu -->
<script type="text/x-magento-init">
    {
        "#click-button": {
            "Tigren_MagentoJS/js/example": {
                "message": "Welcome to Tigren Clothings !"
            }
        }
    }
</script>
